### ISSUE TITLE
Incompatibility  "expo-constants": "~15.4.5"  version on the new update  

### ISSUE THREAD

**Issue by AbdulmalekAlshugaa** [statsig-io/react-native-expo#10]
"I'm currently using 'expo-constants': '~14.4.2' in my base code, while the Statsig library is using 'expo-constants': '~15.4.5', which leads to a crash during the native build process. When I remove Statsig from my source code, the app works fine. Is there a fix or a version that I can update to that uses the ~14.4.2 version of expo-constants?"

**Comment by tore-statsig** [comment]
Are you able to update to 15.x.x of expo-constants?

**Comment by tore-statsig** [comment]
should be resolved in v4.7.1 https://github.com/statsig-io/react-native-expo/pull/12
