### ISSUE TITLE
Error on initialization

### ISSUE THREAD

**Issue by ericyliu** [statsig-io/react-native-expo#7]
Tried to initialize with both StatsigProvider and Statsig.initialize, but getting an error:

` [Statsig] An unexpected exception occurred. [TypeError: Cannot read property 'getRandomBase64String' of undefined]`
 
 I have tried to initialize with a user and without a user.

I am using:

```
"statsig-react-native-expo": "^4.6.1",
"expo": "~49.0.5",
```

**Comment by dan-loomb** [comment]
Are you able to install `react-native-get-random-values` and try again?

```
npm install react-native-get-random-values
```

Our ReactNative (https://docs.statsig.com/client/reactNativeSDK) documentation mentions this as a required step. It's possible that this is a documentation issue and we should include these steps as part of the ReactNative Expo flow.

**Comment by ericyliu** [comment]
tried that, and tried installing `expo-random`, neither fixed it. digging through the code for that package though, i think im just using an unsupported Expo version. Looking at https://github.com/LinusU/react-native-get-random-values/blob/master/index.js#L34, it expects `global.ExpoModules.ExpoRandom` to exist but it doesn't in Expo 49. ExpoModules has also been deprecated in this version.

*edit* used the fix suggested here to get it working in Expo 49 and with expo-router (to get a shim in for ExpoCrypto): https://github.com/expo/expo/issues/17270#issuecomment-1684266602

**Comment by tore-statsig** [comment]
Thanks for leaving the details for future folks who come across the issue, glad you were able to get it resolved
