### ISSUE TITLE
No updates to expo packages

### ISSUE THREAD

**Issue by robertoyoc** [statsig-io/react-native-expo#8]
It has been a while since this package was updated, expo doctor is throwing warnings around the libraries used inside statsig react native.
Any plans to update this library soon?

**Comment by vijaye-statsig** [comment]
@daniel-statsig

**Comment by smrubin** [comment]
+1

**Comment by smrubin** [comment]
@tore-statsig @vijaye-statsig Any updates on a timeline for this?

**Comment by vijaye-statsig** [comment]
Apologies for dropping this - following up on this internally

**Comment by tore-statsig** [comment]
We're taking a look now, sorry for the delay.  We do have a major refactor coming which will enable us to push updates to this package more regularly moving forwards.  That will likely land around the March/April timeline

**Comment by tore-statsig** [comment]
I was hoping this was a simple package bump - turns out we need to clean up a bit more along the way.  I've started that and will update here when we have the new version out

**Comment by MBasiak** [comment]
@tore-statsig What's status of that? We are observing warnings about Statsig dependencies for a while.

**Comment by tore-statsig** [comment]
That was landed in react, which should unblock this, but we turned back to the refactor I mentioned previous - my appologies, we should have done the fix here first.  I'll turn back to that now

Here are the docs for the new sdk which we will be moving towards soon - still finalizing react/react native/expo, but as an FYI

https://docs.statsig.com/client/javascript-sdk/expo

**Comment by tore-statsig** [comment]
This should be resolved by https://github.com/statsig-io/react-native-expo/releases/tag/v4.7.0
